@startuml
title Automatically Set Metadata and Allow User to Modify Metadata (FRs 47-50)

|user| User
|mobile| Mobile App
|backend| Backend
|db| Supabase

|user|
start
:Opens app;
:Navigates to "Collections" page;
:Creates a collection;

|mobile|
:Sets the collection's location from the keepsakes' metadata;
:Sets the collection's date/time from the keepsakes' metadata;
:Makes call to Update Collection API;

|backend|
:Update location and date/time for collection on database;

|db|
:Updates location and date/time for collection;

|mobile|
:Display collection with updated metadata;

|user|
:Clicks on button to modify collection's metadata;

|mobile|
:Open window to edit metadata fields;

|user|
:Enters updated metadata;
:Submits updated metadata;

|mobile|
:Makes call to Update Collection API;

|backend|
:Update collection's metadata on database;

|db|
:Updates location and date/time for collection;

|mobile|
:Display collection with updated metadata;

stop
@enduml
