---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: sh -c 'cd backend && poetry run black .'
        language: system
        types: [python]

      - id: ruff
        name: Check with Ruff
        entry: sh -c 'cd backend && poetry run ruff check server tests --fix'
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: Validate types with MyPy
        entry: sh -c 'cd backend && poetry run mypy server'
        language: system
        types: [python]
        pass_filenames: false
