// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { HealthCheckApiHealthGetData, SendEchoMessageApiEchoPostData, SendEchoMessageApiEchoPostResponse, SendEchoMessageApiEchoPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 * Checks the health of a project.
 *
 * It returns 200 if the project is healthy.
 */
export const healthCheckApiHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckApiHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>({
        url: '/api/health',
        ...options
    });
};

/**
 * Send Echo Message
 * Sends echo back to user.
 *
 * :param incoming_message: incoming message.
 * :returns: message same as the incoming.
 */
export const sendEchoMessageApiEchoPost = <ThrowOnError extends boolean = false>(options: Options<SendEchoMessageApiEchoPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SendEchoMessageApiEchoPostResponse, SendEchoMessageApiEchoPostError, ThrowOnError>({
        url: '/api/echo/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};