// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Simple message model.
 */
export type Message = {
    message: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SendEchoMessageApiEchoPostData = {
    body: Message;
    path?: never;
    query?: never;
    url: '/api/echo/';
};

export type SendEchoMessageApiEchoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendEchoMessageApiEchoPostError = SendEchoMessageApiEchoPostErrors[keyof SendEchoMessageApiEchoPostErrors];

export type SendEchoMessageApiEchoPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SendEchoMessageApiEchoPostResponse = SendEchoMessageApiEchoPostResponses[keyof SendEchoMessageApiEchoPostResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};