---
repos:
  - repo: local
    hooks:
      - id: pnpm-lint
        name: Lint with pnpm
        entry: bash -c 'cd app && pnpm lint'
        language: system
        files: \.(js|jsx|ts|tsx)$

      - id: pnpm-test
        name: Test with pnpm
        entry: bash -c 'cd app && pnpm test'
        language: system
        files: \.(js|jsx|ts|tsx)$